import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [lambdaResponse, setLambdaResponse] = useState();

  useEffect(() => {
    console.log("inside useeffect");
  });
  const makeLambdaCall = async () => {
    try {
      const response = await fetch("/api/lambdaCall/", {
        method: "GET",
        headers: {
          Accept: "application/json",
        },
      });

      const text = await response.json();
      console.log("text :", text);

      if (response.status === 200) {
        console.log("coming to 200 success : ", text);
        console.log("coming to 200 ?? ", text.success.message);
        setLambdaResponse(text.success.message);
      }
    } catch (error) {
      console.log("tools catch block");
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS app and Calling Lambda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          className="extractJsonButton"
          type="button"
          onClick={makeLambdaCall}
        >
          Call Lambda
        </button>
        
        {lambdaResponse ? lambdaResponse : "Waiting..."}

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
